name: merge-pull-request-concurrency
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true    

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Something is better than nothing"
          sleep 30
